repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-toml
# flake8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-bugbear
        - flake8-comprehensions
        - flake8-eradicate
        - flake8-print
        - flake8-string-format
        - pep8-naming
        args: [--config, .flake8]

-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: poetry run pytest
      always_run: true
      pass_filenames: false
      stages: [commit]
